# Generated by Django 4.2.7 on 2023-11-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('rental', 'rental'), ('solid', 'solid')], max_length=50),
        ),
    ]
