# Generated by Django 4.2.7 on 2023-11-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0002_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='retal_price_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
