# Generated by Django 4.2.7 on 2023-11-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_book_retal_price_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='retal_price_rental',
            new_name='total_rental',
        ),
    ]
